import { keyframes } from 'styled-components';
import { ColorValue } from '../../../../helpers/colors';

export const blink = keyframes({
  '0%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '9rem',
    borderRadius: '50%',
    borderTop: `2rem solid ${ColorValue.lightBlue}`,
  },
  '1%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '8rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '1.2%': {
    top: '16rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '6rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '1.4%': {
    top: '16.4rem',
    left: '11.35rem',
    width: '5.8rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5rem solid ${ColorValue.lightBlue}`,
  },
  '1.6%': {
    top: '16.4rem',
    left: '11.5rem',
    width: '5.5rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5.7rem solid ${ColorValue.lightBlue}`,
  },
  '1.8%': {
    top: '16.4rem',
    left: '11.35rem',
    width: '5.8rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5rem solid ${ColorValue.lightBlue}`,
  },
  '2%': {
    top: '16rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '6rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '2.2%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '9rem',
    borderRadius: '50%',
    borderTop: `2rem solid ${ColorValue.lightBlue}`,
  },
  '48.4%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '9rem',
    borderRadius: '50%',
    borderTop: `2rem solid ${ColorValue.lightBlue}`,
  },
  '48.6%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '8rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '48.8%': {
    top: '16rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '6rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '49%': {
    top: '16.4rem',
    left: '11.35rem',
    width: '5.8rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5rem solid ${ColorValue.lightBlue}`,
  },
  '49.2%': {
    top: '16.4rem',
    left: '11.5rem',
    width: '5.5rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5.7rem solid ${ColorValue.lightBlue}`,
  },
  '49.4%': {
    top: '16.4rem',
    left: '11.35rem',
    width: '5.8rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5rem solid ${ColorValue.lightBlue}`,
  },
  '49.6%': {
    top: '16rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '6rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '49.8%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '9rem',
    borderRadius: '50%',
    borderTop: `2rem solid ${ColorValue.lightBlue}`,
  },
  '50%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '9rem',
    borderRadius: '50%',
    borderTop: `2rem solid ${ColorValue.lightBlue}`,
  },
  '50.2%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '8rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '50.4%': {
    top: '16rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '6rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '50.6%': {
    top: '16.4rem',
    left: '11.35rem',
    width: '5.8rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5rem solid ${ColorValue.lightBlue}`,
  },
  '50.8%': {
    top: '16.4rem',
    left: '11.5rem',
    width: '5.5rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5.7rem solid ${ColorValue.lightBlue}`,
  },
  '51%': {
    top: '16.4rem',
    left: '11.35rem',
    width: '5.8rem',
    height: '3rem',
    borderRadius: '50%',
    borderTop: `5rem solid ${ColorValue.lightBlue}`,
  },
  '51.2%': {
    top: '16rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '6rem',
    borderRadius: '50%',
    borderTop: `4rem solid ${ColorValue.lightBlue}`,
  },
  '51.4%': {
    top: '15rem',
    left: '11.3rem',
    width: '5.9rem',
    height: '9rem',
    borderRadius: '50%',
    borderTop: `2rem solid ${ColorValue.lightBlue}`,
  },
});
